### ISSUE TITLE
Create course card component ("my courses") section

### ISSUE THREAD

**Issue by VirginiaBalseiro** [Junior-Devs/2020-Junior-Devs-Project#26]
### Create a component for course card in the "my courses" section: 

![image](https://user-images.githubusercontent.com/28412960/80810116-6e156180-8bc3-11ea-817e-38578aa7a43b.png)

### Requirements: 

- [ ] Create the component
- [ ] Create a story on Storybook
- [ ] Hard code the title, description and other texts for now. There will be a ticket to update this in the future.
- [ ] Write tests - we'll use https://github.com/testing-library/react-testing-library
- [ ] Link to design where you can find the CSS: https://www.figma.com/file/HNLdpIu2S7kV0G03By3Sh1/Elearning-Platform-(home)?node-id=1%3A3

**Comment by deboragaleano** [comment]
Hi @VirginiaBalseiro, I'd like to give this one a try, if possible !

**Comment by VirginiaBalseiro** [comment]
Assigned @deboragaleano ! Please comment on the #contributions channel that you will be working on this for visibility, thanks!
